### PR TITLE
[NEW] Add Koji request handle

### PR DESCRIPTION
**Pull request by shiqimei**
This PR aims to add basic RokcetChat APIs for koji mini-apps calling.

### CODE REVIEW

**Comment by kb0304** [comment]
@lolimay Can we remove package.json and package-lock.json changes from this PR?

**Comment by shiqimei** [comment]
> @lolimay Can we remove package.json and package-lock.json changes from this PR?

OK

**Comment by shiqimei** [comment]
Done!

**Comment by kb0304** [comment]
Already reviewed in #2

**Pull request closed without merging**
